version: '3.9'
services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu_plesk
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -f /dev/null
    entrypoint: ["/bin/bash", "-c"]
    stdin_open: true
    tty: true
    restart: always
    networks:
      - localhost-network
    environment:
      - DEBIAN_FRONTEND=noninteractive
    init: true

  plesk:
    image: plesk/plesk
    container_name: plesk_server
    privileged: true
    ports:
      - "8880:8880"  # Expõe a porta corretamente
      - "443:443"    # HTTPS, caso necessário
      - "80:80"      # HTTP, caso necessário
    restart: always
    networks:
      - localhost-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1450:1433"
    networks:
      - localhost-network
    restart: always

  backend:
    build: ./backend
    container_name: php_backend
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - sqlserver
    ports:
      - "8000:80"
    networks:
      - localhost-network

  grapesjs:
    build: ./grapesjs
    container_name: grapesjs_server
    volumes:
      - ./grapesjs:/app
    ports:
      - "8080:8080"
    networks:
      - localhost-network
    depends_on:
      - backend
    restart: always

networks:
  localhost-network:
    driver: bridge
